logging:
    level:
        root: INFO
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD:example}
        url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:example}
        username: ${POSTGRES_USERNAME:example}
    jpa:
        hibernate:
            ddl-auto: update
